//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class App_Server
    {
        public App_Server()
        {
            this.Esperienza_App_Server = new HashSet<Esperienza_App_Server>();
            this.Cv = new HashSet<Cv>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<Esperienza_App_Server> Esperienza_App_Server { get; set; }
        public virtual ICollection<Cv> Cv { get; set; }
    }
    
}
