//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Certificazione
    {
        public Certificazione()
        {
            this.Cv_certificazione = new HashSet<Cv_certificazione>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string ente_rilascio { get; set; }
    
        public virtual ICollection<Cv_certificazione> Cv_certificazione { get; set; }
    }
    
}
