//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Cv
    {
        public Cv()
        {
            this.Cv_certificazione = new HashSet<Cv_certificazione>();
            this.Cv_Esperienza = new HashSet<Cv_Esperienza>();
            this.Lingua = new HashSet<Lingua>();
            this.Ambiente_Ide = new HashSet<Ambiente_Ide>();
            this.App_Server = new HashSet<App_Server>();
            this.Db = new HashSet<Db>();
            this.Framework = new HashSet<Framework>();
            this.Linguaggio = new HashSet<Linguaggio>();
            this.Versioning_Configuration = new HashSet<Versioning_Configuration>();
        }
    
        public int id { get; set; }
        public int fk_dipendente { get; set; }
        public bool IsCompleto { get; set; }
    
        public virtual ICollection<Cv_certificazione> Cv_certificazione { get; set; }
        public virtual Dipendente Dipendente { get; set; }
        public virtual ICollection<Cv_Esperienza> Cv_Esperienza { get; set; }
        public virtual ICollection<Lingua> Lingua { get; set; }
        public virtual ICollection<Ambiente_Ide> Ambiente_Ide { get; set; }
        public virtual ICollection<App_Server> App_Server { get; set; }
        public virtual ICollection<Db> Db { get; set; }
        public virtual ICollection<Framework> Framework { get; set; }
        public virtual ICollection<Linguaggio> Linguaggio { get; set; }
        public virtual ICollection<Versioning_Configuration> Versioning_Configuration { get; set; }
    }
    
}
