//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Cv_Esperienza
    {
        public int fk_esperienza { get; set; }
        public int fk_Cv { get; set; }
        public System.DateTime data_inizio { get; set; }
        public System.DateTime data_fine { get; set; }
    
        public virtual Cv Cv { get; set; }
        public virtual Esperienza Esperienza { get; set; }
    }
    
}
