//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Esperienza_App_Server
    {
        public int fk_Esperienza { get; set; }
        public int fk_App_Server { get; set; }
    
        public virtual App_Server App_Server { get; set; }
        public virtual Esperienza Esperienza { get; set; }
    }
    
}
