//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Lingua
    {
        public int fk_Cv { get; set; }
        public int fk_Tipo_lingua { get; set; }
        public int lettura { get; set; }
        public int scrittura { get; set; }
        public int parlato { get; set; }
    
        public virtual Cv Cv { get; set; }
        public virtual Valutazione Lingua_scrittura { get; set; }
        public virtual Valutazione Lingua_parlato { get; set; }
        public virtual Valutazione Lingua_lettura { get; set; }
        public virtual Tipo_lingua Tipo_lingua { get; set; }
    }
    
}
