//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Linguaggio
    {
        public Linguaggio()
        {
            this.Cv = new HashSet<Cv>();
            this.Esperienza = new HashSet<Esperienza>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<Cv> Cv { get; set; }
        public virtual ICollection<Esperienza> Esperienza { get; set; }
    }
    
}
