//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace CurricolumDAL
{
    public partial class GestioneCVEntities : DbContext
    {
        public GestioneCVEntities()
            : base("name=GestioneCVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ambiente_Ide> Ambiente_Ide { get; set; }
        public DbSet<App_Server> App_Server { get; set; }
        public DbSet<Certificazione> Certificazione { get; set; }
        public DbSet<Cv> Cv { get; set; }
        public DbSet<Cv_certificazione> Cv_certificazione { get; set; }
        public DbSet<Cv_Esperienza> Cv_Esperienza { get; set; }
        public DbSet<Db> Db { get; set; }
        public DbSet<Dipendente> Dipendente { get; set; }
        public DbSet<Esperienza> Esperienza { get; set; }
        public DbSet<Esperienza_App_Server> Esperienza_App_Server { get; set; }
        public DbSet<Framework> Framework { get; set; }
        public DbSet<Lingua> Lingua { get; set; }
        public DbSet<Linguaggio> Linguaggio { get; set; }
        public DbSet<Ruolo> Ruolo { get; set; }
        public DbSet<Tipo_lingua> Tipo_lingua { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Valutazione> Valutazione { get; set; }
        public DbSet<Versioning_Configuration> Versioning_Configuration { get; set; }
    }
}
