//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Ruolo
    {
        public Ruolo()
        {
            this.User = new HashSet<User>();
        }
    
        public int id { get; set; }
        public string tipo_ruolo { get; set; }
    
        public virtual ICollection<User> User { get; set; }
    }
    
}
