//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Tipo_lingua
    {
        public Tipo_lingua()
        {
            this.Lingua = new HashSet<Lingua>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
    
        public virtual ICollection<Lingua> Lingua { get; set; }
    }
    
}
