//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CurricolumDAL
{
    public partial class Valutazione
    {
        public Valutazione()
        {
            this.Scrittura_list = new HashSet<Lingua>();
            this.Parlato_list = new HashSet<Lingua>();
            this.Lettura_list = new HashSet<Lingua>();
        }
    
        public int id { get; set; }
        public string nome_valutazione { get; set; }
    
        public virtual ICollection<Lingua> Scrittura_list { get; set; }
        public virtual ICollection<Lingua> Parlato_list { get; set; }
        public virtual ICollection<Lingua> Lettura_list { get; set; }
    }
    
}
